### ISSUE TITLE
Single Ignition/Retraction Issue

### ISSUE THREAD

**Issue by 772pilot** [neskweek/LightSaberOS#1]
Lightsaber only powers on / powers off once. After that, the saber becomes unresponsive - buttons do nothing, no sound is played, and LEDs remain off. While the saber is on, however, it functions as expected - swings detected, blaster mode can be entered/exited, and lockup activated. Upon powering off lightsaber, "L" LED aboard nano remains lit for 1s and extinguishes (otherwise, it is solid). 

Config menu works as expected only from boot. Can be entered/exited multiple times without issue, but cannot be accessed after power on/power off when the saber becomes unresponsive. 

Problem persists on two different Nano clone boards ([these](http://www.amazon.com/OSOYOO-ATMEGA328P-Module-Micro-controller-Arduino/dp/B00UACD13Q/ref=sr_1_1?s=electronics&ie=UTF8&qid=1458249970&sr=1-1&keywords=arduino+nano)) with CH340G USB serial chips (not FTDI). Issue was not encountered the first few times code was compiled/uploaded to Nano. Tried resetting the board with blank sketch and reuploading LSOS - no success.

Commented LS_INFO and uncommented LS_DEBUG, LS_BUTTON_DEBUG, LS_RELAUNCH_DEBUG, and LS_DEBUG_SLEEP in Config. Serial monitor returns "Main button click" upon power on and "Main button longPress start" and "Main button longPress..." during power off. Doesn't seem to iterate "Main button longPress..." like it does for entering config menu. Also does not seem to detect the button being released.

**Comment by 772pilot** [comment]
Updated with more info.

**Comment by neskweek** [comment]
I finally was able to burn a new bootloader correctly on my Nano clone, so I was able to make some debugging:

Problem source found and corrected in v1.0.1 :

Nano clones seems to have a problem with the code of the first retractation effect :
The  "_for_" instruction of this effect made the clone boards crash.
I replace its counter type to uint8_t to int8_t and it now works OK.

Still makes me think those clones have flaws :P

**Comment by 772pilot** [comment]
Works like a beauty now! Thank you! Who would've thought that uint8_t would've been so pesky.
