### ISSUE TITLE
Saber locks up with too much interrupt

### ISSUE THREAD

**Issue by DJWing79** [neskweek/LightSaberOS#14]
Ok so I tried my sabers out at my wedding and we had one break on me (physically) but the others worked until you either left them on for about 5 min or swung them around a lot (twirling)...if you left it on it would suddenly cut the audio but keep light on and you'd have to kill battery in order to fix it....with the swinging it would suddenly loop a small portion of audio and become unresponsive...likewise I had to cut battery and then it worked fine

**Comment by neskweek** [comment]
Hello
should be corrected by v1.0.4
