### ISSUE TITLE
Saber freezes while in action mode

### ISSUE THREAD

**Issue by Mawg1** [neskweek/LightSaberOS#16]
Hi,
I have the latest release from June 20, 2016 and I am still experience some difficulties.  the saber is perfectly happy in standby and config mode.  However, once Action mode is entered the Saber will freeze - this happens randomly between 10 and 60 seconds.  Any thoughts or help would be greatly appreciated! 

Thanks

**Comment by neskweek** [comment]
Hello
Sorry to read this ...
Let me repeat this to be sure I understand correctly: you launch action mode you leave it on a table (for example) and it hangs rapidly ?

Sorry to ask this one : are you sure you haven't got any short cuts ? (believe me, some are tricky to detect, and if it is, there's nothing I can do , code wise, to correct this.)
If no :
What device are you using (Official Arduino Nano, or clone )? 
What kind of LED type are you using ?
what kind of flicker effect do you use (if ledstring) ?

**Comment by Mawg1** [comment]
Hi nesweek,

Once I launch action mode the saber will freeze up very quickly.   I have let it sit on the table and it freezes anywhere between 20 and 60 second.   If I swing it and clash it,  it will freeze up as well (about 30 to 60 seconds).

I'm pretty confident I don't have shorts.  I actually built two separate setups to try and troubleshoot.   One uses and official arduino with the FTDI chip,  the other uses the CH34OG chip.   Both behave the same.   Both setups use RGB leds - right now they are cheap thru hole ones while I wait on my tri-rebel.  They do flicker though.   

Only other thing I can think of is that I am using arduino ide to program.   I could never get eclipse to run properly. 

Thanks for your time! 
Mike

**Comment by neskweek** [comment]
Hi 

Did you wire your device according to the plan in the wiki  especially SPK- and SPK+ ?
if yes, in Config.h uncomment line 176 : 
//#define LS_INFO
and in Light.cpp comment lines 463 and 470 : 
#ifdef LS_HEAVY_DEBUG
...
#endif

then plug your device, upload the sketch. Then open the serial monitor (Ctrl+shift+M).
Start action mode.
wait until it hangs. Then copy what's on screen and send it here so I can see what's going on.

Cheers

**Comment by Mawg1** [comment]
Hi, 

I did double checked the wiring and it is according to the schematic on everything.  I'm traveling but will try this first thing monday morning.  Thank you again for all the help!

**Comment by jbkuma** [comment]
I've had a similar issue with v1.0 and v1.1 the serial keeps outputting values, but the buttons become unresponsive.  I can't tell exactly when it hangs because it continues outputting serial info and sound.

**Comment by neskweek** [comment]
Hello,
Please try with latest version (1.2.2).

Also please double check your wirings/soldering for short cuts or deffective solderings, especially around  your butttons / kill key port.

I also had this kind of problems but each time it was due to insulations problems.
The fact that the device keeps printing on serial prove the device didn't hang.
