### ISSUE TITLE
LSOS 1.2.2 on Arduino clone unable to connect to DFPlayer

### ISSUE THREAD

**Issue by 772pilot** [neskweek/LightSaberOS#20]
Using Arduino IDE v1.6.5-r5. LSOS is unable to start; serial monitor indicates that setup stops at DFPlayer connection and loops repeatedly. A repeated pop from the speaker is audible and the following output is shown on the monitor:

```
L01
Connecting to DFPlayer...
Connected to DFPlayer !
Á²¥L01
Connecting to DFPlayer...
Connected to DFPlayer !
Á²¥˜01
Connecting to DFPlayer...
Connected to DFPlayer !
Á²¥˜01
Connecting to DFPlayer...
Connected to DFPlayer !
Á²¥L01
Connecting to DFPlayer...
Connected to DFPlayer !
Á²¥L01
Connecting to DFPlayer...
Connected to DFPlayer !
Á²¥
```

TX light also flashes continuously.

**Comment by neskweek** [comment]
It does connect to DFPlayer, it bugs after...
Have you previously customize you soundfont.h ?

**Comment by 772pilot** [comment]
Soundfont.h is completely unedited.

**Comment by neskweek** [comment]
what happen if you augment this delay (at end of setup) ?: 

```
dfplayer.setSerial(DFPLAYER_TX, DFPLAYER_RX);
dfplayer.setVolume(storage.volume);
delay(200);
pinMode(SPK1, INPUT);
pinMode(SPK2, INPUT);
```

**Comment by 772pilot** [comment]
Changing the delay interval changes the time between speaker pops.

**Comment by neskweek** [comment]
:)
Ok... so it changes nothing ...

I don't see where it can come from ....

Ok let's see if it comes from setup or loop.

Please add : 
Serial.println(F("TestA"));
at end of setup() and then tell me if you see it before the crash on serial.

Refresh my memories please : what's your config ?

**Comment by 772pilot** [comment]
Same output:

```
L01
Connecting to DFPlayer...
Connected to DFPlayer !
Á²¥L01
Connecting to DFPlayer...
Connected to DFPlayer !
Á²¥L01
Connecting to DFPlayer...
Connected to DFPlayer !
Á²¥L01
Connecting to DFPlayer...
Connected to DFPlayer !
Á²¥

```

**Comment by neskweek** [comment]
ok ...

Refresh my memories please : what's your config ?
Did you plugged dfplayer SPK1 and SPK2 to the arduino ? and if yes where ?

Hopefully there's only 3 simple instructions to incriminate... and I think those are faulty :

pinMode(SPK1, INPUT);
pinMode(SPK2, INPUT);

please comment out and tell the results ;)

**Comment by 772pilot** [comment]
LED string setup with Arduino nano clone, MPU6050, and DFPlayer mini. No modifications at this time.

SPK1 and SPK2 are connected to pins A0 and A1, respectively.  Commenting the two lines above doesn't seem to change anything.

**Comment by neskweek** [comment]
ok ...weird.

Have you changed SPK1 and SPK2 value in Config.h (I changed those since last version to A6 and A7)

the pop comes from dfplayer initialisation. Since the delay augment it's frequency, we pass setVolume and delay ...

try to comment those then : 

```
soundFont.setID(storage.soundFont);

/***** DF PLAYER INITIALISATION  *****/

//setup finished. Boot ready. We notify !
dfplayer.playPhysicalTrack(16);
```

**Comment by 772pilot** [comment]
Oh, I didn't realize those had been changed. I seem to get the same behavior even if I modify SPK1 and SPK2.  I'm sorry, I'm a little confused. Did you want me to comment the quoted code, or the setVolume and delay functions that come before?

**Comment by neskweek** [comment]
the quoted ones ;)

**Comment by 772pilot** [comment]
That seems to do the trick, however there is no sound.

**Comment by neskweek** [comment]
ok .... so uncomment everything ...
except this : 
dfplayer.playPhysicalTrack(16);

**Comment by 772pilot** [comment]
Doing that causes the loop issue again.

EDIT: I believe the problem line is this one: soundFont.setID(storage.soundFont);

**Comment by neskweek** [comment]
damn then uncomment out this one and comment : 

soundFont.setID(storage.soundFont);

if this stops the problem (you still have no sound) add : 
Serial.print(F("storage.soundFont :"));
Serial.println(storage.soundFont);

and show me what you get on serial please.

**Comment by 772pilot** [comment]
Ah, I think the issue has been resolved. I removed the 3rd case from Soundfont.h and all is well. I previously had a 3rd soundfont stored in EEPROM, I'm guessing the value doesn't get erased when I reupload a new sketch?

**Comment by neskweek** [comment]
That's what I was starting to suspect, that's why I asked you about your previous config, but I omitt to ask you about Soundfont.h.
change this too in soundfont.h

#define SOUNDFONT_QUANTITY 1

I'll remove the case 3 since there's no font attached to this case to avoid anymore problems.
Thanks ;)

Tell me what you think about swing detection

**Comment by 772pilot** [comment]
Very nice! Had to turn down the sensitivity quite a bit, but it's very responsive.

**Comment by neskweek** [comment]
Thank you 
I did the changes.
If all is ok I'll close this one ;)

**Comment by 772pilot** [comment]
Okay!
