### ISSUE TITLE
A bit confused with OS uploading...

### ISSUE THREAD

**Issue by LightOSproblems** [neskweek/LightSaberOS#22]
Hi neskweek!

Your project is just awesome! I'm building a lightsaber with same electronics, but i have a problem. I keep trying to upload the OS just as in your tutorial, but it just isn't working for me... 
 So I know it might be too much to be asked, but i still ask you: Could you please make a detailed video tutorial of uploading and maybe even building one of those sound boards?

Best wishes

**Comment by Protonerd** [comment]
I can help with the soundboard topic: just order a DIYino Prime, then you have everything you need integrated on a tiny board.
As to the programming, if you have installed the Arduino IDE (refer to the Arduino page for instructions) and you have the right drivers, it must work.

**Comment by LightOSproblems** [comment]
Hi!

Thanks for answer. I recently bought a new arduino nano and uploading worked on it :) . Because I have already other parts shipping and I started building the system, I won't buy the DIYino Prime this time.

stay cheeki breeki
