### ISSUE TITLE
Settings Correction for Neopixel

### ISSUE THREAD

**Issue by DJWing79** [neskweek/LightSaberOS#25]
In a previous ticket you told me if I wire Negative through a N-Fet I needed to do something...but I am not understanding what you meant. Where in the code would I make the change?

**Comment by DJWing79** [comment]
Also, I have the RGBW neopixels, I think it's throwing the code off, any way to change the settings from RGB to RGBW?

**Comment by DJWing79** [comment]
Also, I got a strand of generic WS2812 and I can't get it to change colors. Its always red and won't cycle in config mode, but when using other test codes I can get it to work, yet when I use Proto's fire code, it will turn on the other colors as I can see blue and green in the power down. Also, the brightness is really dim, even when I set it higher

**Comment by DJWing79** [comment]
NM, figured out the RGB setting, needed to specify pin 3 (my NFET) as String 1, but still having issues with RGBW, it won't change colors correctly

**Comment by Protonerd** [comment]
LSOS does not support RGBW type neopixels. Due to current consumption considerations this support is alno not planned.
