### ISSUE TITLE
Sound files corrupted

### ISSUE THREAD

**Issue by markturansky** [neskweek/LightSaberOS#29]
When attempting to extract SDCard.7z on Mac OSX (Sierra) using The Unarchiver, I get the error message "Could not extra the file "..." from the archive "SDCard.7z": The archive file is corrupted"

This happens for all files in the archive.

**Comment by faeton13** [comment]
Have you tryed to download it once again?

**Comment by markturansky** [comment]
I tried opening the archive via what I got from 'git clone' and I also just attempted to download the archive directly from github. Same error (the archive hasn't changed, so I wouldn't expect that to work).

**Comment by per1234** [comment]
Works for me using 7-Zip.

**Comment by Protonerd** [comment]
Please, as mentioned by per1234, use 7-zip (free ware, works perfectly!). I close the issue.
