### ISSUE TITLE
Eclipse

### ISSUE THREAD

**Issue by Soulbp** [neskweek/LightSaberOS#4]
I'm confused with eclipse, it seems v2.2 is the only one with x64. It does not seem to have the option you mentioned in the arduino section. Also which arduino version is recommended as it complains that mine is newer than the version of eclipse or is this a non-issue?

Edit:
N/m I thhink I did not scroll far enough.

In the Lightsaberos-master I don't see he main loop, Shouldn't there be a LightSaberOS.cpp generated by the project that has the basic setup in and loop? LightSaberOS-Master has Light, ConFigMenu and Buttons.

**Comment by neskweek** [comment]
Please read Carefully. From readme.md  :

> WHAT YOU WILL NEED :
> 
> Java Runtime Environment 8 Download the right file for your architecture
> Arduino Eclipse **v.2016-03-11_03-29-38** Again, download the right file for your architecture

[...]

> SET UP YOUR PC:
> 
> Download and install Java Runtime Environment 8
> Download the right file for your OS
> Download Arduino Eclipse **v.2016-03-11_03-29-38**

**Comment by Soulbp** [comment]
Thank you my original issue was simply not going down far enough on the download page. However unless I'm missing something where is your main loop and setup functions handled? You've done a lot of work here that's for sure. I'm trying to get up to speed with out it all fits together.

**Comment by Soulbp** [comment]
Again my mistake it was in LightSaber.ino, why is it named this way instead of .cpp? I ran build all it did not seem to give any errors, hopefully I'll get my sound soon I have everything else. Thank you for your hard work.

**Comment by neskweek** [comment]
Hello :)
Thank you 

In Arduino IDE, the main file wears .ino or .pde extension. I just kept that.

Cheers
