### ISSUE TITLE
Sharp buzz after playing menu sound files

### ISSUE THREAD

**Issue by 772pilot** [neskweek/LightSaberOS#51]
I've encountered an issue where a sharp buzz will play from the speaker immediately after a non-soundfont audio file has played. This includes boot sounds, menu navigation files, and jukebox files. However, audio functions normally when the saber is in action mode.  I've attached a video demonstrating the bug. NOTE: This is all happening over a USB connection. I have not yet moved to battery testing.

Video of issue (30 second clip): [https://youtu.be/0jRbk4iWHkA](https://youtu.be/0jRbk4iWHkA)

I'm running a slightly modified version of LSOS 1.3 (only lighting is modified) in a luxeon configuration.  Hardware is standard: chinese clone nano, MPU6050, and DFPlayer. I'm also using the Arduino IDE (ver. 1.8.1, board ver. 1.6.11).

It's worth noting that this issue only popped up after I resolved a previous issue where no sound was being played AT ALL (DFPlayer red indicator LED was not lighting up). The Arduino IDE compiler told me there was a conflict between multiple instances of DFPlayer.h so I renamed the "DFPlayer" folder to "DFPlayerOLD" and elected to use "DFPlayer_LSOS" as the only library. It was only after this that I noticed the buzzing. As a sanity check, I removed both the "DFPlayerOLD" and "DFPlayer_Mini_Mp3" folders from the libraries folder, but that didn't change anything.

Any ideas as to what could be causing the issue and how to fix it? 

EDIT:
I should note, all sound files have a sampling rate of either 44100 or 22050 Hz, and they are all 16-bit.

**Comment by jbkuma** [comment]
It sounds like what happens if there is meta data in the file.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by Vulkan1** [comment]
I get that as well but less noticeable. Mine is ignorable but I believe it's clicks more or less with mine.

**Comment by 772pilot** [comment]
Wow, it didn't even occur to me it could be the metadata. Everything works perfectly after stripping it all, thanks!
