### ISSUE TITLE
SoundGap before a swing

### ISSUE THREAD

**Issue by Stiffartic** [neskweek/LightSaberOS#60]
I'm noticing a little gap in the sound before each time I swing, but there's no gaps before a clash sound (only some very random times). I'm using the "base soundpack".

**Comment by jbkuma** [comment]
Do you mean the sound pack included in the repository?

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by Stiffartic** [comment]
Yeah! With that pack!
