### ISSUE TITLE
DFPlayer Behavior on LSOS 1.5

### ISSUE THREAD

**Issue by a-elkaim** [neskweek/LightSaberOS#68]
I am having troubles with my DFPlayer, the volume is correctly set, but it keeps looping on "Soundfont" sound and doesn't play anything.

I have tried with the old library, and it is sometimes working.

What can I do to fix this ?

**Comment by DRagonenko** [comment]
try the modes with the usual LEDs on newpixel it happens

**Comment by a-elkaim** [comment]
I kinda figured it out, why my arduino nano is loaded with too much code (90% of the space), the whole system behaves weirdly...

I think I'll rewrite some features when I have to time so that they are cleaner and lighter

**Comment by a-elkaim** [comment]
I'm sorry to re-open this issue but I'm really struggling getting this feature to work.

My arduino is 83% full and the DFPlayer is still stuck on looping "soundfont" ...

Can anyone help me ?

**Comment by a-elkaim** [comment]
It was an hardware issue, switched to another dfplayer and it works fine
