### ISSUE TITLE
Errors with eclipse

### ISSUE THREAD

**Issue by LightOSproblems** [neskweek/LightSaberOS#9]
Hello!
I opened the OS in eclipse and it has errors...many of them say "type uint16_t could not be resolved" etc. What should I do?

![eclipse errors](https://cloud.githubusercontent.com/assets/18902086/14942582/94e733da-0fc9-11e6-9cd1-038c6a51a571.png)

**Comment by neskweek** [comment]
Hello

Debugging an eclipse installation on a distant PC is not quite easy to do. And I can't tell what is going wrong on your eclipse installation there.

On the other hand, Pert, another coder has sended a patch, that would allow LSOS to be compiled with Arduino IDE. It might be released soon 

Cheers

**Comment by LightOSproblems** [comment]
Hello
Thanks for the feedback! Waiting for the patch file. :)
